service: ez-contract-backend

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-ignore

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  environment:
    LOCAL_DB_URI: 'mongodb://localhost/ez-contract'
    AWS_SECRET: ez-contract
    STAGE: ${self:provider.stage}
    S3_BUCKET: ez-contract-backend
    INFURA_MAINNET: https://mainnet.infura.io/v3/
    INFURA_ROPSTEN: https://ropsten.infura.io/v3/
    INFURA_RYNKEBY: https://rinkeby.infura.io/v3/
    INFURA_KOVAN: https://kovan.infura.io/v3/
    INFURA_GOERLI: https://goerli.infura.io/v3/

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get
          cors: true